'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const out = path.join(root, 'src', 'generated');
fs.mkdirSync(out, { recursive: true });
const marker = '// Generated by StaticTableGenerator.';
for (const file of ['calculate.cjs', 'calculate.d.ts', 'manifest.cjs', 'enums.cjs', 'enums.d.ts']) {
  const target = path.join(out, file);
  if (!fs.existsSync(target) || !fs.readFileSync(target, 'utf8').startsWith(marker)) {
    throw new Error(`Missing generated ${file}. Run Task 10 in StaticTableGenerator first.`);
  }
}
console.log('Generated Node.js SDK sources are present.');
